### ISSUE TITLE
List of Figures

### ISSUE THREAD

**Issue by jlaura** [shumway/asudis#8]
Question: I have two figures in my introduction (Chapter 1).  What in asudis.sty needs to be modified so that the 'Figure' and 'Page' headers are placed in the correct place.

![figureheader](https://cloud.githubusercontent.com/assets/2105468/9266435/d443c4f0-41f5-11e5-8798-afca931c24dc.png)

**Comment by joelelynn** [comment]
jlaura, I worked quite a bit on getting the headings "Figure" and "Page" to be in the right place for my dissertation. I vaguely remember discovering this issue once I'd already graduated. Someone else trying to use the format also had a figure in chapter 1 and had the same result. As I recall, something really small seems to fix this. In your main TeX file, dis.tex perhaps, switch the order of the commands `\listoffigures` and `\addtocontents{lof}{Figure~\hfill Page \par}`. Let me know if that works for you. Unfortunately, I've forgotten why this fixes the problem, so all I have to offer if it works is a magic solution with no explanation.

**Comment by joelelynn** [comment]
jlaura, did you try the suggestion I made in my last comment?

**Comment by jlaura** [comment]
Joel,

I will give this a go today - I was on travel Friday - this AM.

Thanks,
Jay

**Comment by jlaura** [comment]
Success.  I moved the right justify 'Page' header to the top of the
definition a la:

\newpage
\addcontentsline{toc}{part}{LIST OF FIGURES}
\addtocontents{lof}{Figure~\hfill Page \par}
\addtocontents{toc}{CHAPTER \par}
\renewcommand{\cftlabel}{Figure}
% This gets the headers for the LOF right on the first page.  Subsequent
pages
% are handled by the fancyhdr code in the asudis.sty file.
\listoffigures

This is in dis.tex, lines 62-69 (though I have some additional package
includes).

Thanks for all of the assistance.

**Comment by joelelynn** [comment]
Jay,

Glad you got it working! I made a commit which moves `\listoffigures` to beyond `\addtocontents{lof}{Figure~\hfill Page \par}` in `dis.tex`, which I think is the fundamental thing to fix this problem. Let me know if you should have any other problems.

Joel
